### ISSUE TITLE
Add an exemple of how to embed the jpeg stream in a custom html page

### ISSUE THREAD

**Issue by HugoSart** [Bronkoknorb/PyImageStream#1]
First of all, congratulations for your work in this project. I have a backend server and a frontend web app (angular 2+). Also, I'm running a stream on port 8888 as default. I'm not figuring out the proper way to show only the stream in my frontend webpage. Maybe using a <video> tag or an <img> tag.
An example of this situation would be great.

**Comment by Bronkoknorb** [comment]
Hi, sorry for the very late response. I did not see your question before.
For an example how to embed the video in an HTML page, have a look at the example file included:
https://github.com/Bronkoknorb/PyImageStream/blob/master/static/index.html

Or, if you are using Angular, you can also check out my other project which embeds this stream (actually two streams) into an angular app:
https://github.com/Bronkoknorb/hm-aquarium/tree/master/aquarium-web/src/app/camera
